### ISSUE TITLE
awk command does not seem to be working with mawk

### ISSUE THREAD

**Issue by CloudMass** [ralgozino/oh-my-kustomize#2]
I have an issue with using this plugin on Ubuntu 22.04. 
It looks like the awk command used on line 4 works with gawk but not mawk.
https://github.com/ralgozino/oh-my-kustomize/blob/7f67bbfc50e4231619d799f97d0078eea15dc068/kustomize.plugin.zsh#L4

```
kustomize version | awk 'match($0, /v([0-9.]+)\s/, m) { print m[1]; }'
awk: line 1: syntax error at or near ,
```

I tested a bit and found that the following should work with both.
match($0, /([0-9.]+) /) { print substr($0, RSTART, RLENGTH) }

I tested using ideone.com & my local installation.
You should be able to see the results here.
https://ideone.com/oL7raY
https://ideone.com/2VG6sO

**Comment by ralgozino** [comment]
Hi @CloudMass 
thank you, your version seems to be working fine, I've committed it.
